Facturacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('principal.urls', 'principal'), namespace='principal')),
    path('inventario/',
         include(('inventario.urls', 'inventario'), namespace='inventario')),
    path('admin/', admin.site.urls),
]

inventario/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaEdit, SubCategoriaView, SubCategoriaNew,SubCategoriaDel,MarcaView,MarcaDel, MarcaEdit, MarcaNew, marca_inactivar

urlpatterns = [
    # Categoria
    path("categorias/", CategoriaView.as_view(), name="categoria"),
    path("categorias/nueva", CategoriaNew.as_view(), name="categoria_new"),
    path("categorias/edit/<int:pk>", CategoriaEdit.as_view(), name="categoria_edit"),
    path("categorias/eliminar/<int:pk>", CategoriaDel.as_view(),name="categoria_eliminar"),

    #Subcategoria
    path("subcategorias/", SubCategoriaView.as_view(), name="subcategoria"),
    path("subcategorias/nueva",SubCategoriaNew.as_view(), name="subcategoria_new"),
    path("subcategorias/edit/<int:pk>", SubCategoriaEdit.as_view(), name="subcategoria_edit"),
    path("subcategorias/eliminar/<int:pk>", SubCategoriaDel.as_view(), name="subcategoria_eliminar"),

    #Marca

    path("marca/", MarcaView.as_view(), name="marca"),
    path("marca/nueva",MarcaNew.as_view(), name="marca_new"),
    path("marca/edit/<int:pk>", MarcaEdit.as_view(), name="marca_edit"),
    path("marca/eliminar/<int:id>", marca_inactivar, name="marca_inactivar"),

]

principal/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from.views import Home
urlpatterns = [
    path("",Home.as_view(), name="home"),
    path('login/',auth_view.LoginView.as_view(template_name='principal/login.html'), name="login"),
    path('logout/', auth_view.LogoutView.as_view(template_name = "principal/login.html"),name="logout")
]

inventario/models.py
from django.db import models

from principal.models import ClaseModelo


class Categoria(ClaseModelo):
    descripcion = models.CharField(max_length=100,
                                   help_text="Descripcion de la Categoria",
                                   unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = "Categorias"


class Subcategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100,
                                   help_text="Descripcion de la Categoria",)

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Subcategoria, self).save()

    class Meta:
        verbose_name_plural = "Sub Categorias"
        unique_together = ('categoria','descripcion')

class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text="Descripcion de la Marca",
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca,self).save()

    class Meta:
        verbose_name_plural = "Marcas"


class UnidadMedida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text="Descripcion de la Unidad de Medida",
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida,self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medida"

principal/models.py
from django.db import models
from django.contrib.auth.models import User


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    usuario_creado = models.ForeignKey(User, on_delete=models.CASCADE)
    usuario_modificado = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True

inventario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from .models import Categoria, Subcategoria, Marca, UnidadMedida
from .form import CategoriaForm, SubCategoriaForm, MarcaForm

####!#  CATEGORIA ###########


class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = 'inventario/categoria_list.html'
    context_object_name = "obj"
    login_url = "principal:login"


class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = Categoria
    template_name = 'inventario/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy("inventario:categoria")
    login_url = "principal:login"

    def form_valid(self, form):
        form.instance.usuario_creado = self.request.user
        return super().form_valid(form)


class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Categoria
    template_name = 'inventario/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy("inventario:categoria")
    login_url = "principal:login"

    def form_valid(self, form):
        form.instance.usuario_modificado = self.request.user.id
        return super().form_valid(form)


class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = Categoria
    template_name = 'inventario/catalogos_del.html'
    context_object_name = "obj"
    success_url = reverse_lazy('inventario:categoria')


###! SUBCATEGORIA ###


class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model = Subcategoria
    template_name = 'inventario/subcategoria_list.html'
    context_object_name = "obj"
    login_url = "principal:login"


class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = Subcategoria
    template_name = 'inventario/subcategoria_form.html'
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inventario:subcategoria")
    login_url = "principal:login"

    def form_valid(self, form):
        form.instance.usuario_creado = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Subcategoria
    template_name = 'inventario/subcategoria_form.html'
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inventario:subcategoria")
    login_url = "principal:login"

    def form_valid(self, form):
        form.instance.usuario_modificado = self.request.user.id
        return super().form_valid(form)


class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = Subcategoria
    template_name = 'inventario/catalogos_del.html'
    context_object_name = "obj"
    success_url = reverse_lazy('inventario:subcategoria')


#!### MARCA ######


class MarcaView(LoginRequiredMixin, generic.ListView):
    model = Marca
    template_name = 'inventario/marca_list.html'
    context_object_name = "obj"
    login_url = "principal:login"


class MarcaNew(LoginRequiredMixin, generic.CreateView):
    model = Marca
    template_name = 'inventario/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy("inventario:marca")
    login_url = "principal:login"

    def form_valid(self, form):
        form.instance.usuario_creado = self.request.user
        return super().form_valid(form)


class MarcaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Marca
    template_name = 'inventario/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy("inventario:marca")
    login_url = "principal:login"

    def form_valid(self, form):
        form.instance.usuario_modificado = self.request.user.id
        return super().form_valid(form)


class MarcaDel(LoginRequiredMixin, generic.DeleteView):
    model = Marca
    template_name = 'inventario/catalogos_del.html'
    context_object_name = "obj"
    success_url = reverse_lazy('inventario:marca')


def marca_inactivar(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto = {}
    template_name = "inventario/catalogos_del.html"

    if not marca:
        return redirect("inventario:marca")

    if request.method == "GET":
        contexto = {'obj': marca}
    
    if request.method == "POST":
        marca.estado = False
        marca.save()
        return redirect("inventario:marca")

    return render(request, template_name, contexto)


#!### UNIDADES DE MEDIDA ######

class UnidadMedidaView(LoginRequiredMixin, generic.ListView):
    model = UnidadMedida
    template_name = 'inventario/unidad_list.html'
    context_object_name = "obj"
    login_url = "principal:login"

# class MarcaNew(LoginRequiredMixin, generic.CreateView):
#     model = UnidadMedida
#     template_name = 'inventario/unidad_form.html'
#     context_object_name = 'obj'
#     form_class = UnidadForm
#     success_url = reverse_lazy("inventario:unidad")
#     login_url = "principal:login"

#     def form_valid(self, form):
#         form.instance.usuario_creado = self.request.user
#         return super().form_valid(form)

inventario/templates/inventario/catalogos_del.html
{% extends 'bases/base.html' %} {% block page_content %}
<form method="post" class="form-inline">

  {% csrf_token %}
  <div class="col-xl-6 col-md-6 mb-6">
    <div class="card border-left-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-warning text-uppercase mb-1"
            >
              Eliminar ? {{ obj.descripcion }}
            </div>
            <button type="submit" class="btn btn-danger"> <i class="far fa-question-circle"> </i> Si, Eliminar</button>

            <!-- <a href="{%url 'inventario:subcategoria' %}" class="btn btn-success">
              <span class="fa fa-undo"> Cancelar </span></a
            > -->

            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"> 
              <span class="fa fa-undo"> Cancelar </span></a
            >

          </div>
          <div class="col-auto">
            <i class="far fa-question-circle fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>

{% endblock page_content %} {%block js_page%} {% endblock js_page %}

inventario/templates/inventario/categoria_form.html
{% extends 'bases/base.html' %} {% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-6 col-md-6 mb-6">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
    <div class="card border-left-success shadow h-100 py-2">
      {% endif %}
        <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-success text-uppercase mb-1"
            >
            {% if obj %} Editar {% else %} Nueva  {% endif %} Categoria
            </div>

            <!-- **************************************** -->
            <div class="dropdownn-divider">
              <div class="row">
                <div class="col-10">
                  <div class="input-group">
                    <input
                      type="text"
                      name="descripcion"
                      id="id_descripcion"
                      maxlength="100"
                      class="form-control"
                      placeholder="Descripcion"
                      value="{% if obj %} {{obj.descripcion}} {% endif %} "
                    />
                  </div>
                </div>

                <div class="col-2">
                  <div class="form-group">
                    <label for="id_estado"> Estado </label>
                    <input
                      type="checkbox"
                      name="estado"
                      id="id_estado"
                      class="form-control"
                      checked
                      {% if obj.estado %} checked {% endif %}                     
                      />
                  </div>
                </div>

                <!-- {{form.as_p}} -->
              </div>
              <div class="dropdown-divider"></div>
              <div class="row">
                <div class="col">
                  <button type="submit" class="btn btn-danger">
                    <span class="fa fa-save"> Guardar </span>
                  </button>
                  <a
                    href="{%url 'inventario:categoria' %}"
                    class="btn btn-success"
                  >
                    <span class="fa fa-undo"> Cancelar </span></a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock page_content %} {%block js_page%} {% endblock %}

inventario/templates/inventario/categoria_list.html
{% extends 'bases/base.html' %} {% block page_content %}

<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="
      card-header
      py-3
      d-flex
      flex-row
      align-items-center
      justify-content-between
    "
  >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones</div>
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %} <div class="alert alert-info"> No hay Categorias </div> 

    {% else %}
    <table class="table table-striped table-hover">
      <thead>
        <th>Id</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>F. Creado</th>
        <th>F. Modifi</th>
        <th class="all">Acciones</th>
      </thead>

      <tbody>
        {% for item in obj %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.descripcion }}</td>
          <td>{{ item.estado }}</td>
          <td>{{ item.fecha_creacion }}</td>
          <td>{{ item.fecha_modificacion }}</td>
          <td>
            <a href="#" class="btn btn-warning btn-circle" role="button">
                <i class="far fa-edit"></i>
            </a>
            
            <a href="#" class="btn btn-danger btn-circle" role="button">
                <i class="far fa-trash-alt"></i>
            </a>
            
          </td>
        </tr>

        {%endfor%}
      </tbody>
    </table>
    {%endif%}
  </div>
</div>

{% endblock page_content %} {% block js_page %} {%endblock js_page%}

inventario/templates/inventario/marca_form.html
{% extends 'bases/base.html' %} 

{% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-12 col-md-12 mb-12">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
    <div class="card border-left-success shadow h-100 py-2">
      {% endif %}
        <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-success text-uppercase mb-1"
            >
            {% if obj %} Editar {% else %} Nueva  {% endif %} SubCategoria
            </div>

            <!-- **************************************** -->
            <div class="dropdownn-divider"> </div>
              <div class="row">
                <div class="col-10">
                  <div class="input-group">
                    {{ form.descripcion }}
                  </div>
                </div>

                <div class="col-2">
                  <div class="form-group">
                      {{ form.estado }}
                  </div>
                </div>

                <!-- {{form.as_p}} -->
              </div>
              <div class="dropdown-divider"></div>
              <div class="row">
                <div class="col">
                  <button type="submit" class="btn btn-danger">
                    <span class="fa fa-save"> Guardar </span>
                  </button>
                  <a
                    href="{%url 'inventario:marca' %}"
                    class="btn btn-success"
                  >
                    <span class="fa fa-undo"> Cancelar </span></a
                  >
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock page_content %} {%block js_page%} {% endblock %}

inventario/templates/inventario/marca_list.html
{% extends 'bases/base.html' %} {% block page_content %}

<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="
      card-header
      py-3
      d-flex
      flex-row
      align-items-center
      justify-content-between
    "
  >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Marcas</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones</div>
        <a class="dropdown-item" href="{% url 'inventario:marca_new' %}"
          ><i class="far fa-calendar-plus"> </i> Nueva</a
        >
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay Marcas</div>

    {% else %}
    <table class="table table-striped table-hover">
      <thead>
        <th>Id</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>F. Creado</th>
        <th>F. Modifi</th>
        <th class="all">Acciones</th>
      </thead>

      <tbody>
        {% for item in obj %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.descripcion }}</td>
          <td>{{ item.estado | yesno:"Activo,Inactivo"}}</td>
          <td>{{ item.fecha_creacion | date:"d/m/Y H:i:s" }}</td>
          <td>{{ item.fecha_modificacion| date:"d/m/Y H:i:s" }}</td>
          <td>
            <a
              href="{% url 'inventario:marca_edit' item.id %}"
              class="btn btn-warning btn-circle"
              role="button"
            >
              <i class="far fa-edit"></i>
            </a>

            <a href="{% url 'inventario:marca_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button">
              <i class="far fa-thumbs-down"></i>
            </a>
          </td>
        </tr>

        {%endfor%}
      </tbody>
    </table>
    {%endif%}
  </div>
</div>

{% endblock page_content %} 


{% block js_page %}

<script>
  $(document).ready(function () {
    $(".table").DataTable();
  });
</script>

{% endblock js_page %}

inventario/templates/inventario/subcategoria_form.html
{% extends 'bases/base.html' %} 

{% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-12 col-md-12 mb-12">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
    <div class="card border-left-success shadow h-100 py-2">
      {% endif %}
        <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-success text-uppercase mb-1"
            >
            {% if obj %} Editar {% else %} Nueva  {% endif %} SubCategoria
            </div>

            <!-- **************************************** -->
            <div class="dropdownn-divider"> </div>
              <div class="row">
                <div class="col-5">
                  <div class="input-group">
                    {{ form.categoria }}
                  </div>
                </div>
                <div class="col-5">
                  <div class="input-group">
                    {{ form.descripcion }}
                  </div>
                </div>

                <div class="col-2">
                  <div class="form-group">
                      {{ form.estado }}
                  </div>
                </div>

                <!-- {{form.as_p}} -->
              </div>
              <div class="dropdown-divider"></div>
              <div class="row">
                <div class="col">
                  <button type="submit" class="btn btn-danger">
                    <span class="fa fa-save"> Guardar </span>
                  </button>
                  <a
                    href="{%url 'inventario:subcategoria' %}"
                    class="btn btn-success"
                  >
                    <span class="fa fa-undo"> Cancelar </span></a
                  >
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock page_content %} {%block js_page%} {% endblock %}

inventario/templates/inventario/subcategoria_list.html
{% extends 'bases/base.html' %} {% block page_content %}

<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="
      card-header
      py-3
      d-flex
      flex-row
      align-items-center
      justify-content-between
    "
  >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Subcategorias</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones</div>
        <a class="dropdown-item" href="{% url 'inventario:subcategoria_new' %}"
          ><i class="far fa-calendar-plus"> </i> Nueva</a
        >
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay Subcategorias</div>

    {% else %}
    <table class="table table-striped table-hover">
      <thead>
        <th>Categoria</th>
        <th>Id</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>F. Creado</th>
        <th>F. Modifi</th>
        <th class="all">Acciones</th>
      </thead>

      <tbody>
        {% for item in obj %}
        <tr>
          <td> {{item.categoria}}</td>
          <td>{{ item.id }}</td>
          <td>{{ item.descripcion }}</td>
          <td>{{ item.estado | yesno:"Activo,Inactivo"}}</td>
          <td>{{ item.fecha_creacion | date:"d/m/Y H:i:s" }}</td>
          <td>{{ item.fecha_modificacion| date:"d/m/Y H:i:s" }}</td>
          <td>
            <a
              href="{% url 'inventario:subcategoria_edit' item.id %}"
              class="btn btn-warning btn-circle"
              role="button"
            >
              <i class="far fa-edit"></i>
            </a>

            <a
              href="{% url 'inventario:subcategoria_eliminar' item.id %}"
              class="btn btn-danger btn-circle"
              role="button"
            >
              <i class="far fa-trash-alt"></i>
            </a>
          </td>
        </tr>

        {%endfor%}
      </tbody>
    </table>
    {%endif%}
  </div>
</div>

{% endblock page_content %} {% block js_page %}

<script>
  $(document).ready(function () {
    $(".table").DataTable();
  });
</script>

{% endblock js_page %}

inventario/templates/inventario/unidad_form.html
{% extends 'bases/base.html' %} 

{% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-12 col-md-12 mb-12">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
    <div class="card border-left-success shadow h-100 py-2">
      {% endif %}
        <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div
              class="text-xs font-weight-bold text-success text-uppercase mb-1"
            >
            {% if obj %} Editar {% else %} Nueva  {% endif %} SubCategoria
            </div>

            <!-- **************************************** -->
            <div class="dropdownn-divider"> </div>
              <div class="row">
                <div class="col-10">
                  <div class="input-group">
                    {{ form.descripcion }}
                  </div>
                </div>

                <div class="col-2">
                  <div class="form-group">
                      {{ form.estado }}
                  </div>
                </div>

                <!-- {{form.as_p}} -->
              </div>
              <div class="dropdown-divider"></div>
              <div class="row">
                <div class="col">
                  <button type="submit" class="btn btn-danger">
                    <span class="fa fa-save"> Guardar </span>
                  </button>
                  <a
                    href="{%url 'inventario:marca' %}"
                    class="btn btn-success"
                  >
                    <span class="fa fa-undo"> Cancelar </span></a
                  >
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock page_content %} {%block js_page%} {% endblock %}

inventario/templates/inventario/unidad_list.html
{% extends 'bases/base.html' %} {% block page_content %}

<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="
      card-header
      py-3
      d-flex
      flex-row
      align-items-center
      justify-content-between
    "
  >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Unidades de Medida</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones</div>
        <a class="dropdown-item" href="{% url 'inventario:unidad_new' %}"
          ><i class="far fa-calendar-plus"> </i> Nueva</a
        >
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay Unidades de Medida</div>

    {% else %}
    <table class="table table-striped table-hover">
      <thead>
        <th>Id</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>F. Creado</th>
        <th>F. Modifi</th>
        <th class="all">Acciones</th>
      </thead>

      <tbody>
        {% for item in obj %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.descripcion }}</td>
          <td>{{ item.estado | yesno:"Activo,Inactivo"}}</td>
          <td>{{ item.fecha_creacion | date:"d/m/Y H:i:s" }}</td>
          <td>{{ item.fecha_modificacion| date:"d/m/Y H:i:s" }}</td>
          <td>
            <a
              href="{% url 'inventario:unidad_edit' item.id %}"
              class="btn btn-warning btn-circle"
              role="button"
            >
              <i class="far fa-edit"></i>
            </a>

            <a href="{% url 'inventario:unidad_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button">
              <i class="far fa-thumbs-down"></i>
            </a>
          </td>
        </tr>

        {%endfor%}
      </tbody>
    </table>
    {%endif%}
  </div>
</div>

{% endblock page_content %} 


{% block js_page %}

<script>
  $(document).ready(function () {
    $(".table").DataTable();
  });
</script>

{% endblock js_page %}